# config_jobspec_template.yaml (Contains ONLY CustomJobSpec fields)

# Service account for the job (optional, part of CustomJobSpec)
# serviceAccount: SERVICE_ACCOUNT_PLACEHOLDER

# Worker pool specs (required part of CustomJobSpec)
workerPoolSpecs:
- machineSpec:
    machineType: cloud-tpu
    acceleratorType: TPU_V3
    acceleratorCount: 8 # For tpu-v3-8 VM count is 1
  replicaCount: 1
  # Container spec (required part of workerPoolSpecs)
  containerSpec:
    imageUri: europe-west4-docker.pkg.dev/verdant-current-452602-s1/flaxdiff-docker-repo/flaxdiff-tpu-trainer:latest
    command: ["wandb"]
    args:
    - agent
    - --count=1
    - umd-projects/mlops-msml605-project/3s98m11b
    env:
    - name: WANDB_API_KEY
      value: fdcf7523bb77b87138aa6bc45da5a28a7ac64270

# You could add other CustomJobSpec fields here if needed, like:
# baseOutputDirectory:
#   outputUriPrefix: gs://your-bucket/output/
# scheduling:
#   timeout: 7200s
#   restartJobOnWorkerRestart: false