apiVersion: apps/v1
kind: Deployment
metadata:
  name: diffusion-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diffusion
  template:
    metadata:
      labels:
        app: diffusion
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-nodepool
                    operator: In
                    values:
                      - high-mem-pool
      containers:
        - name: api
          image: us-central1-docker.pkg.dev/mlops-msml605-project/diffusion-repo/diffusion-inference-pipeline:v2
          imagePullPolicy: Always
          resources:
            requests:
              memory: "4Gi"
              cpu: "1"
            limits:
              memory: "8Gi"
              cpu: "2"
          ports:
            - containerPort: 8000
          env:
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wandb-api-key
                  key: WANDB_API_KEY
