apiVersion: apps/v1
kind: Deployment
metadata:
  name: diffusion-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diffusion
  template:
    metadata:
      labels:
        app: diffusion
    spec:
      containers:
        - name: api
          image: gcr.io/umd-project-456120/diffusion-api
          imagePullPolicy: Always
          resources:
            requests:
              memory: "4Gi"
              cpu: "1"
            limits:
              memory: "8Gi"
              cpu: "2"
          ports:
            - containerPort: 8000
          env:
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wandb-api-key
                  key: WANDB_API_KEY
