apiVersion: v1
kind: Service
metadata:
  name: diffusion-service
spec:
  selector:
    app: diffusion-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80            # External port
      targetPort: 8000    # Internal container port
